export const LAYOUT_UPDATEDATABASES = 'LAYOUT/UPDATEDATABASES';
export const LAYOUT_UPDATECOLLECTIONS = 'LAYOUT/UPDATECOLLECTIONS';
export const LAYOUT_SELECTDATABASE = 'LAYOUT/SELECTDATABASE';
export const LAYOUT_SELECTCOLLECTION = 'LAYOUT/SELECTCOLLECTION';
export const LAYOUT_UPDATEDATALIST = 'LAYOUT/UPDATEDATALIST';
export const LAYOUT_SETDATABASES = 'LAYOUT/SETDATABASES';
export const LAYOUT_SETDATALIST = 'LAYOUT/SETDATALIST';

export const LAYOUT_GETDATABASES = 'LAYOUT/GETDATABASES';